[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.8.5"
ratatui = "0.29.0"
strum = "0.26.3"
strum_macros = "0.26.4"
